name: Get latest release versions

on:
  push:
    paths:
      - ".github/workflows/schedule.yml"
    branches:
      - master
  schedule:
    - cron: "0 10 * * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 1

      - name: Fetch new app versions
        run: |
          find ./build -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | while read app; do
            if test -f "./build/${app}/latest-version.sh"; then
              version=$(bash "./build/${app}/latest-version.sh")
              if [[ ! -z "${version}" || "${version}" != "null" ]]; then
                echo "${version}" | tee "./build/${app}/.version" > /dev/null
                echo "${app} ${version}"
              fi
            fi
          done

      - name: Fetch csi-external-attacher release version
        run: |
          curl -sL https://api.github.com/repos/kubernetes-csi/external-attacher/releases/latest | \
          jq -r ".tag_name" | cut -c 2- > build/csi-external-attacher/.version

      - name: Fetch csi-external-provisioner release version
        run: |
          curl -sL https://api.github.com/repos/kubernetes-csi/external-provisioner/releases/latest | \
          jq -r ".tag_name" | cut -c 2- > build/csi-external-provisioner/.version

      - name: Fetch csi-external-resizer release version
        run: |
          curl -sL https://api.github.com/repos/kubernetes-csi/external-resizer/releases/latest | \
          jq -r ".tag_name" | cut -c 2- > build/csi-external-resizer/.version

      - name: Fetch csi-node-driver-registrar release version
        run: |
          curl -sL https://api.github.com/repos/kubernetes-csi/node-driver-registrar/releases/latest | \
          jq -r ".tag_name" | cut -c 2- > build/csi-node-driver-registrar/.version

      - name: Fetch csi-external-snapshotter release version
        run: |
          curl -sL https://api.github.com/repos/kubernetes-csi/external-snapshotter/releases/latest | \
          jq -r ".tag_name" | cut -c 2- > build/csi-external-snapshotter/.version

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Github Bot'
          git config --global user.email 'bot@users.noreply.github.com'
          git add -A
          git commit -sam "[Auto Generation] Adding new release version" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
